In [67]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

In [68]:
df = pd.read_csv("heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [69]:
X = df.drop(["HeartDisease"], axis="columns")
y = df.HeartDisease

In [70]:
encode = LabelEncoder()

encode.fit(X.Sex)
X.Sex = encode.transform(X.Sex)

encode.fit(X.RestingECG)
X.RestingECG = encode.transform(X.RestingECG)

encode.fit(X.ExerciseAngina)
X.ExerciseAngina = encode.transform(X.ExerciseAngina)

X.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,1,ATA,140,289,0,1,172,0,0.0,Up
1,49,0,NAP,160,180,0,1,156,0,1.0,Flat
2,37,1,ATA,130,283,0,2,98,0,0.0,Up
3,48,0,ASY,138,214,0,1,108,1,1.5,Flat
4,54,1,NAP,150,195,0,1,122,0,0.0,Up

In [71]:
import numpy as np

np.unique(X.ST_Slope)

array(['Down', 'Flat', 'Up'], dtype=object)

In [73]:
np.unique(X.ChestPainType)

array(['ASY', 'ATA', 'NAP', 'TA'], dtype=object)

In [74]:
X = pd.concat([X, pd.get_dummies(X.ChestPainType)], axis=1)
X = pd.concat([X, pd.get_dummies(X.ST_Slope)], axis=1)
X = X.drop(["ChestPainType", "ST_Slope"], axis="columns")
X.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ASY,ATA,NAP,TA,Down,Flat,Up
0,40,1,140,289,0,1,172,0,0.0,0,1,0,0,0,0,1
1,49,0,160,180,0,1,156,0,1.0,0,0,1,0,0,1,0
2,37,1,130,283,0,2,98,0,0.0,0,1,0,0,0,0,1
3,48,0,138,214,0,1,108,1,1.5,1,0,0,0,0,1,0
4,54,1,150,195,0,1,122,0,0.0,0,0,1,0,0,0,1

In [76]:
scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X)
X_scaled

array([[0.24489796, 1.        , 0.7       , ..., 0.        , 0.        ,
        1.        ],
       [0.42857143, 0.        , 0.8       , ..., 0.        , 1.        ,
        0.        ],
       [0.18367347, 1.        , 0.65      , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.59183673, 1.        , 0.65      , ..., 0.        , 1.        ,
        0.        ],
       [0.59183673, 0.        , 0.65      , ..., 0.        , 1.        ,
        0.        ],
       [0.20408163, 1.        , 0.69      , ..., 0.        , 0.        ,
        1.        ]])

In [79]:
vis = pd.DataFrame(X_scaled)
vis.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.244898,1.0,0.70,0.479270,0.0,0.5,0.788732,0.0,0.295455,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.428571,0.0,0.80,0.298507,0.0,0.5,0.676056,0.0,0.409091,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.183673,1.0,0.65,0.469320,0.0,1.0,0.267606,0.0,0.295455,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,0.408163,0.0,0.69,0.354892,0.0,0.5,0.338028,1.0,0.465909,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.530612,1.0,0.75,0.323383,0.0,0.5,0.436620,0.0,0.295455,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [81]:
X.describe()

,Age,Sex,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ASY,ATA,NAP,TA,Down,Flat,Up
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,0.789760,132.396514,198.799564,0.233115,0.989107,136.809368,0.404139,0.887364,0.540305,0.188453,0.221133,0.050109,0.068627,0.501089,0.430283
std,9.432617,0.407701,18.514154,109.384145,0.423046,0.631671,25.460334,0.490992,1.066570,0.498645,0.391287,0.415236,0.218289,0.252957,0.500271,0.495386
min,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,60.000000,0.000000,-2.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.000000,1.000000,120.000000,173.250000,0.000000,1.000000,120.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,54.000000,1.000000,130.000000,223.000000,0.000000,1.000000,138.000000,0.000000,0.600000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,60.000000,1.000000,140.000000,267.000000,0.000000,1.000000,156.000000,1.000000,1.500000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,77.000000,1.000000,200.000000,603.000000,1.000000,2.000000,202.000000,1.000000,6.200000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2)

In [86]:
model = SVC()
model.fit(X_train, y_train)

SVC()

In [126]:
model.score(X_test, y_test)

0.8641304347826086

In [167]:
from sklearn.decomposition import PCA

pca = PCA(0.96)
X_pca = pca.fit_transform(X_scaled)
X_pca

array([[ 1.16651672, -0.22288285,  0.37936734, ..., -0.05881045,
        -0.10862988, -0.19932073],
       [ 0.15495621,  1.26601995,  0.24800286, ...,  0.16804305,
        -0.10234759, -0.09094618],
       [ 1.10229019, -0.25837269,  0.33251737, ...,  0.18099386,
        -0.07315052, -0.02624051],
       ...,
       [-1.01620276, -0.10382394,  0.20700043, ..., -0.07933041,
         0.0049521 ,  0.07945177],
       [ 0.29245175,  0.69731197,  1.20263593, ..., -0.04877839,
        -0.19673681,  0.05657387],
       [ 1.05443163,  0.37290403, -0.5583542 , ..., -0.05646991,
        -0.07050125, -0.27264733]])

In [168]:
X_train, X_test, y_train, y_test = train_test_split(X_pca, y, test_size=0.2)

In [169]:
model = SVC()
model.fit(X_train, y_train)

SVC()

In [170]:
model.score(X_test, y_test)

0.8967391304347826